### ISSUE TITLE
Unable to close popup

### ISSUE THREAD

**Issue by Thedijje** [laravelLiveIndia/laravellive-2019#23]
![image](https://user-images.githubusercontent.com/1737771/51106901-368a7680-1813-11e9-9f81-a58b23b3d194.png)

After submitting the Email address for early bird, unable to close popup by clicking close button or clicking outside of popup area.
Only Esc key is working to close the popup.

**Comment by shivanisehdev86** [comment]
Thanks for reporting issue resolved in latest update
